### ISSUE TITLE
PrefixList.xml

### ISSUE THREAD

**Issue by otalado** [W6OP/CallParser#1]
Is  **PrefixList.xml** a regularly maintained list? If so, where I can download it from?
Regards Vladimir, S53C

**Comment by W6OP** [comment]
The PrefixList is owned and maintained by Alex Shovkoplyas VE3NEA.

**Comment by otalado** [comment]
Tnx for the reply.  I only found a file http://dxatlas.com/DxAtlas/Files/DxAtlasTables.zip, but the data is not in XML format. I cannot find any other reference. Do you have a download link for the PrefixList.xml or do I need to contact VE3NEA for it??

**Comment by W6OP** [comment]
you will have to contact Alex directly.

**Comment by otalado** [comment]
I contacted Alex, who kindly provided me with a fresh version of the prefix file. Thank you.
